#!/usr/bin/env bash
# Usage: ./0-world-wide-web <domain> [<subdomain>]
# Display information about subdomains.

# Function to retrieve and display information about a subdomain
domain_information() {
    # Perform DNS lookup for the subdomain under the specified domain
    nslookup_output=$(dig "$2"."$1" +short 2>&1)

    if echo "$nslookup_output" | grep -q "can't resolve"; then
        echo "Error: Unable to resolve $2.$1"
    else
        record_type=$(echo "$nslookup_output" | awk 'NR==1 {print $1}')
        destination=$(echo "$nslookup_output" | awk 'NR==1 {print $2}')
        echo "The subdomain $2 is a $record_type record and points to $destination"
    fi
}

# Check the number of arguments passed to the script
if [ $# -lt 1 ]; then
    echo "Usage: $0 <domain> [<subdomain>]"
    exit 1
fi

domain="$1"
subdomain="$2"

# If only domain is provided, display information for default subdomains
if [ $# -eq 1 ]; then
    domain_information "$domain" "www"
    domain_information "$domain" "lb-01"
    domain_information "$domain" "web-01"
    domain_information "$domain" "web-02"
fi

# If domain and subdomain are provided, display information for the specified subdomain
if [ $# -eq 2 ]; then
    domain_information "$domain" "$subdomain"
fi
